name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Type check & Lint
        run: |
          npm run lint || true
      - name: Build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'placeholder' }}
        run: npm run build
      - name: Health route smoke test
        run: |
          node -e "const fs=require('fs');console.log('Build complete');"
